# Configurações para PostgreSQL (Produção - Supabase)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://aws-1-us-west-2.pooler.supabase.com:5432/postgres?currentSchema=livraria}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:postgres.jdsgehsflfwzlatcrjpj}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:YKDkuwPYMJFflBoi}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Força o uso do schema correto
spring.jpa.properties.hibernate.default_schema=livraria

# Correção para criação de tabelas em schemas específicos no Postgres
spring.jpa.properties.hibernate.jdbc.lob.non_contextual_creation=true
